name: Run every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # каждые 2 часа
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      MAIN_TOKEN: ${{ secrets.MAIN_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure secrets
        run: |
          if [ -z "$MAIN_TOKEN" ] || [ -z "$BOT_TOKEN" ]; then echo "Missing MAIN_TOKEN or BOT_TOKEN" >&2; exit 1; fi

      - name: Run script
        run: python FarmWinsAlmaz-durakonline-main/main.py
